name: CI + Docker Build & Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Build & Dockerize Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Backend
        working-directory: digital-banking-spring-backend
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build Docker image Backend
        run: docker build -t elmoutaquielmehdi/ebanking-backend:latest digital-banking-spring-backend

      - name: Push Docker image Backend
        run: docker push elmoutaquielmehdi/ebanking-backend:latest

  frontend:
    name: Build & Dockerize Frontend
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: digital-banking-angular-front
        run: npm install

      - name: Build Angular App
        working-directory: digital-banking-angular-front
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build Docker image Frontend
        run: docker build -t elmoutaquielmehdi/ebanking-frontend:latest digital-banking-angular-front

      - name: Push Docker image Frontend
        run: docker push elmoutaquielmehdi/ebanking-frontend:latest
